version: '3'
services:
    db:
      image: postgres
      container_name: postgresdb
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: database_development
      volumes:
        - ./pgdata:/var/lib/postgresql/data
      ports:
        - "5432"
      networks:
        - production-network

    node1:
      build:
          dockerfile: ./docker/node.dockerfile
          context: .
      image: node
      container_name: node
      ports:
          - "3000"
      networks:
          - production-network
      depends_on:
          - "db"

networks:
    production-network:
        driver: bridge
